spring:
  security:
    oauth2:
      client:
        registration:
            google:
              clientId: 571255071509-brqgp8ps19aukqc9nlrsb28jls956a32.apps.googleusercontent.com
              clientSecret: O4E79eyUyEv5bjIPNi9M55ul
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 450082375979662
              clientSecret: 42ffe5aa7379e8326387e0fe16f34132
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect