spring:
  security:
    oauth2:
      client:
        registration:
            google:
              clientId: 96777051241-vf52uf2hg7kbcv3qtaarcek14cn17pe6.apps.googleusercontent.com
              clientSecret: dwlCDU_rw981OfNg6pes8Dx9
              redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 450082375979662
              clientSecret: 42ffe5aa7379e8326387e0fe16f34132
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect